services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://user:password@host.docker.internal:5432/expenses?sslmode=disable
      - JWT_SECRET=your_secret_key
